# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alex/Repos/turing-machine-sdl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alex/Repos/turing-machine-sdl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Repos/turing-machine-sdl/CMakeFiles /home/alex/Repos/turing-machine-sdl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Repos/turing-machine-sdl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sdl-turing-machine

# Build rule for target.
sdl-turing-machine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sdl-turing-machine
.PHONY : sdl-turing-machine

# fast build rule for target.
sdl-turing-machine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/build
.PHONY : sdl-turing-machine/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/main.cpp.s
.PHONY : main.cpp.s

src/controllers/turing_machine.o: src/controllers/turing_machine.cpp.o
.PHONY : src/controllers/turing_machine.o

# target to build an object file
src/controllers/turing_machine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/controllers/turing_machine.cpp.o
.PHONY : src/controllers/turing_machine.cpp.o

src/controllers/turing_machine.i: src/controllers/turing_machine.cpp.i
.PHONY : src/controllers/turing_machine.i

# target to preprocess a source file
src/controllers/turing_machine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/controllers/turing_machine.cpp.i
.PHONY : src/controllers/turing_machine.cpp.i

src/controllers/turing_machine.s: src/controllers/turing_machine.cpp.s
.PHONY : src/controllers/turing_machine.s

# target to generate assembly for a file
src/controllers/turing_machine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/controllers/turing_machine.cpp.s
.PHONY : src/controllers/turing_machine.cpp.s

src/controllers/ui_input.o: src/controllers/ui_input.cpp.o
.PHONY : src/controllers/ui_input.o

# target to build an object file
src/controllers/ui_input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/controllers/ui_input.cpp.o
.PHONY : src/controllers/ui_input.cpp.o

src/controllers/ui_input.i: src/controllers/ui_input.cpp.i
.PHONY : src/controllers/ui_input.i

# target to preprocess a source file
src/controllers/ui_input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/controllers/ui_input.cpp.i
.PHONY : src/controllers/ui_input.cpp.i

src/controllers/ui_input.s: src/controllers/ui_input.cpp.s
.PHONY : src/controllers/ui_input.s

# target to generate assembly for a file
src/controllers/ui_input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/controllers/ui_input.cpp.s
.PHONY : src/controllers/ui_input.cpp.s

src/models/turing_machine_fsm.o: src/models/turing_machine_fsm.cpp.o
.PHONY : src/models/turing_machine_fsm.o

# target to build an object file
src/models/turing_machine_fsm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/models/turing_machine_fsm.cpp.o
.PHONY : src/models/turing_machine_fsm.cpp.o

src/models/turing_machine_fsm.i: src/models/turing_machine_fsm.cpp.i
.PHONY : src/models/turing_machine_fsm.i

# target to preprocess a source file
src/models/turing_machine_fsm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/models/turing_machine_fsm.cpp.i
.PHONY : src/models/turing_machine_fsm.cpp.i

src/models/turing_machine_fsm.s: src/models/turing_machine_fsm.cpp.s
.PHONY : src/models/turing_machine_fsm.s

# target to generate assembly for a file
src/models/turing_machine_fsm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/models/turing_machine_fsm.cpp.s
.PHONY : src/models/turing_machine_fsm.cpp.s

src/models/ui_state.o: src/models/ui_state.cpp.o
.PHONY : src/models/ui_state.o

# target to build an object file
src/models/ui_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/models/ui_state.cpp.o
.PHONY : src/models/ui_state.cpp.o

src/models/ui_state.i: src/models/ui_state.cpp.i
.PHONY : src/models/ui_state.i

# target to preprocess a source file
src/models/ui_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/models/ui_state.cpp.i
.PHONY : src/models/ui_state.cpp.i

src/models/ui_state.s: src/models/ui_state.cpp.s
.PHONY : src/models/ui_state.s

# target to generate assembly for a file
src/models/ui_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/models/ui_state.cpp.s
.PHONY : src/models/ui_state.cpp.s

src/util/colour.o: src/util/colour.cpp.o
.PHONY : src/util/colour.o

# target to build an object file
src/util/colour.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/util/colour.cpp.o
.PHONY : src/util/colour.cpp.o

src/util/colour.i: src/util/colour.cpp.i
.PHONY : src/util/colour.i

# target to preprocess a source file
src/util/colour.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/util/colour.cpp.i
.PHONY : src/util/colour.cpp.i

src/util/colour.s: src/util/colour.cpp.s
.PHONY : src/util/colour.s

# target to generate assembly for a file
src/util/colour.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/util/colour.cpp.s
.PHONY : src/util/colour.cpp.s

src/views/display.o: src/views/display.cpp.o
.PHONY : src/views/display.o

# target to build an object file
src/views/display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/views/display.cpp.o
.PHONY : src/views/display.cpp.o

src/views/display.i: src/views/display.cpp.i
.PHONY : src/views/display.i

# target to preprocess a source file
src/views/display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/views/display.cpp.i
.PHONY : src/views/display.cpp.i

src/views/display.s: src/views/display.cpp.s
.PHONY : src/views/display.s

# target to generate assembly for a file
src/views/display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/views/display.cpp.s
.PHONY : src/views/display.cpp.s

src/views/texture_builder.o: src/views/texture_builder.cpp.o
.PHONY : src/views/texture_builder.o

# target to build an object file
src/views/texture_builder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/views/texture_builder.cpp.o
.PHONY : src/views/texture_builder.cpp.o

src/views/texture_builder.i: src/views/texture_builder.cpp.i
.PHONY : src/views/texture_builder.i

# target to preprocess a source file
src/views/texture_builder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/views/texture_builder.cpp.i
.PHONY : src/views/texture_builder.cpp.i

src/views/texture_builder.s: src/views/texture_builder.cpp.s
.PHONY : src/views/texture_builder.s

# target to generate assembly for a file
src/views/texture_builder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/views/texture_builder.cpp.s
.PHONY : src/views/texture_builder.cpp.s

src/views/ui/build_turing_machine_ui_definition.o: src/views/ui/build_turing_machine_ui_definition.cpp.o
.PHONY : src/views/ui/build_turing_machine_ui_definition.o

# target to build an object file
src/views/ui/build_turing_machine_ui_definition.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/views/ui/build_turing_machine_ui_definition.cpp.o
.PHONY : src/views/ui/build_turing_machine_ui_definition.cpp.o

src/views/ui/build_turing_machine_ui_definition.i: src/views/ui/build_turing_machine_ui_definition.cpp.i
.PHONY : src/views/ui/build_turing_machine_ui_definition.i

# target to preprocess a source file
src/views/ui/build_turing_machine_ui_definition.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/views/ui/build_turing_machine_ui_definition.cpp.i
.PHONY : src/views/ui/build_turing_machine_ui_definition.cpp.i

src/views/ui/build_turing_machine_ui_definition.s: src/views/ui/build_turing_machine_ui_definition.cpp.s
.PHONY : src/views/ui/build_turing_machine_ui_definition.s

# target to generate assembly for a file
src/views/ui/build_turing_machine_ui_definition.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/views/ui/build_turing_machine_ui_definition.cpp.s
.PHONY : src/views/ui/build_turing_machine_ui_definition.cpp.s

src/views/ui/ui.o: src/views/ui/ui.cpp.o
.PHONY : src/views/ui/ui.o

# target to build an object file
src/views/ui/ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/views/ui/ui.cpp.o
.PHONY : src/views/ui/ui.cpp.o

src/views/ui/ui.i: src/views/ui/ui.cpp.i
.PHONY : src/views/ui/ui.i

# target to preprocess a source file
src/views/ui/ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/views/ui/ui.cpp.i
.PHONY : src/views/ui/ui.cpp.i

src/views/ui/ui.s: src/views/ui/ui.cpp.s
.PHONY : src/views/ui/ui.s

# target to generate assembly for a file
src/views/ui/ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/views/ui/ui.cpp.s
.PHONY : src/views/ui/ui.cpp.s

src/views/ui/ui_input.o: src/views/ui/ui_input.cpp.o
.PHONY : src/views/ui/ui_input.o

# target to build an object file
src/views/ui/ui_input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/views/ui/ui_input.cpp.o
.PHONY : src/views/ui/ui_input.cpp.o

src/views/ui/ui_input.i: src/views/ui/ui_input.cpp.i
.PHONY : src/views/ui/ui_input.i

# target to preprocess a source file
src/views/ui/ui_input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/views/ui/ui_input.cpp.i
.PHONY : src/views/ui/ui_input.cpp.i

src/views/ui/ui_input.s: src/views/ui/ui_input.cpp.s
.PHONY : src/views/ui/ui_input.s

# target to generate assembly for a file
src/views/ui/ui_input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl-turing-machine.dir/build.make CMakeFiles/sdl-turing-machine.dir/src/views/ui/ui_input.cpp.s
.PHONY : src/views/ui/ui_input.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sdl-turing-machine"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/controllers/turing_machine.o"
	@echo "... src/controllers/turing_machine.i"
	@echo "... src/controllers/turing_machine.s"
	@echo "... src/controllers/ui_input.o"
	@echo "... src/controllers/ui_input.i"
	@echo "... src/controllers/ui_input.s"
	@echo "... src/models/turing_machine_fsm.o"
	@echo "... src/models/turing_machine_fsm.i"
	@echo "... src/models/turing_machine_fsm.s"
	@echo "... src/models/ui_state.o"
	@echo "... src/models/ui_state.i"
	@echo "... src/models/ui_state.s"
	@echo "... src/util/colour.o"
	@echo "... src/util/colour.i"
	@echo "... src/util/colour.s"
	@echo "... src/views/display.o"
	@echo "... src/views/display.i"
	@echo "... src/views/display.s"
	@echo "... src/views/texture_builder.o"
	@echo "... src/views/texture_builder.i"
	@echo "... src/views/texture_builder.s"
	@echo "... src/views/ui/build_turing_machine_ui_definition.o"
	@echo "... src/views/ui/build_turing_machine_ui_definition.i"
	@echo "... src/views/ui/build_turing_machine_ui_definition.s"
	@echo "... src/views/ui/ui.o"
	@echo "... src/views/ui/ui.i"
	@echo "... src/views/ui/ui.s"
	@echo "... src/views/ui/ui_input.o"
	@echo "... src/views/ui/ui_input.i"
	@echo "... src/views/ui/ui_input.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

